import type { Subgraph } from "./graph.js";
import type { DetectionFinding } from "./types.js";
import { getProvider } from "./providers/index.js";
import { loadSkill } from "./skill-loader.js";

// The narrative is GENERATED by the model, grounded in the shared entity graph.
// Like detection and assessment, the system prompt is NOT hardcoded — it is a
// loadable SKILL FILE. The harness reads the skill body and uses it as the system
// prompt, so narrative is parameterised by a skill exactly like every other
// reasoning node. The graph is the guardrail: the model may only connect entities
// that exist as nodes, which is what makes this "graph-grounded" rather than free
// narration.
const NARRATIVE_SKILL_PATH = "skills/narrative/narrate-host-activity.md";

export async function synthesizeNarrative(
  findings: readonly DetectionFinding[],
  graph: Subgraph,
): Promise<string> {
  if (!findings.length) return "No findings were available to synthesize.";

  const skill = await loadSkill(NARRATIVE_SKILL_PATH);
  const provider = getProvider();
  const userPrompt = [
    "## DetectionFindings",
    JSON.stringify(findings, null, 2),
    "",
    "## Shared Entity Graph",
    "Nodes:",
    ...graph.nodes.map((node) => `- ${node.type}: ${node.label} (${node.id})`),
    "",
    "Edges:",
    ...graph.edges.map((edge) => `- ${edge.source} --${edge.label}--> ${edge.target}`),
    "",
    "Write the campaign narrative now, connecting the findings through these shared entities.",
  ].join("\n");

  const result = await provider.invoke({
    systemPrompt: skill.body,
    userPrompt,
  });
  return result.text;
}
